create table if not exists public.daily_boards (
    id bigint generated by default as identity primary key,
    slate_date date not null unique,
    generated_at timestamptz not null default now(),
    model_version text not null,
    status text not null default 'published'
        check (status in ('draft', 'published', 'completed'))
);

create table if not exists public.board_picks (
    id bigint generated by default as identity primary key,
    board_id bigint not null
        references public.daily_boards(id)
        on delete cascade,

    rank integer not null
        check (rank between 1 and 10),

    player_name text not null,
    team text not null,
    opponent text not null,

    prop_type text not null default 'hits',
    line double precision not null,
    side text not null default 'over'
        check (side in ('over', 'under')),

    model_probability double precision not null
        check (
            model_probability >= 0
            and model_probability <= 1
        ),

    game_time timestamptz,

    result_status text not null default 'pending'
        check (
            result_status in (
                'pending',
                'hit',
                'miss',
                'push',
                'postponed',
                'canceled'
            )
        ),

    unique (board_id, rank)
);

create index if not exists board_picks_board_id_idx
    on public.board_picks(board_id);

alter table public.daily_boards enable row level security;
alter table public.board_picks enable row level security;
