create extension if not exists pgcrypto;

create table if not exists public.daily_boards (
    id bigint generated by default as identity primary key,
    slate_date date not null unique,
    generated_at timestamptz not null default now(),
    model_version text not null,
    status text not null default 'published'
        check (status in ('draft', 'published', 'completed')),
    metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.prop_ingestion_runs (
    id uuid primary key default gen_random_uuid(),
    provider text not null,
    sport_key text not null,
    market_key text not null,
    bookmaker_key text not null,
    started_at timestamptz not null default now(),
    completed_at timestamptz,
    status text not null
        check (status in ('running', 'completed', 'failed')),
    events_found integer not null default 0,
    events_processed integer not null default 0,
    offers_saved integer not null default 0,
    error_message text,
    metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.prop_snapshots (
    id bigint generated by default as identity primary key,
    ingestion_run_id uuid not null
        references public.prop_ingestion_runs(id)
        on delete cascade,
    provider text not null,
    provider_event_id text not null,
    sport_key text not null,
    commence_time timestamptz not null,
    home_team text not null,
    away_team text not null,
    bookmaker_key text not null,
    bookmaker_title text,
    market_key text not null,
    outcome_name text not null,
    player_name text not null,
    line double precision not null,
    price_american integer,
    dfs_odds_type text,
    market_last_update timestamptz,
    source_recorded_at timestamptz,
    source_book_updated_at timestamptz,
    captured_at timestamptz not null,
    raw_payload jsonb not null default '{}'::jsonb
);

create table if not exists public.model_runs (
    id uuid primary key default gen_random_uuid(),
    ingestion_run_id uuid not null
        references public.prop_ingestion_runs(id),
    run_type text not null,
    model_version text not null,
    feature_version text not null,
    started_at timestamptz not null default now(),
    completed_at timestamptz,
    status text not null
        check (status in ('running', 'completed', 'failed')),
    candidate_count integer not null default 0,
    published_count integer not null default 0,
    error_message text,
    metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.board_picks (
    id bigint generated by default as identity primary key,
    board_id bigint not null
        references public.daily_boards(id)
        on delete cascade,

    rank integer not null
        check (rank between 1 and 10),

    player_name text not null,
    team text not null,
    opponent text not null,

    prop_type text not null default 'hits',
    line double precision not null,
    side text not null default 'over'
        check (side in ('over', 'under')),

    model_probability double precision not null
        check (
            model_probability >= 0
            and model_probability <= 1
        ),

    game_time timestamptz,

    result_status text not null default 'pending'
        check (
            result_status in (
                'pending',
                'hit',
                'miss',
                'push',
                'postponed',
                'canceled'
            )
        ),

    prop_snapshot_id bigint
        references public.prop_snapshots(id),
    model_run_id uuid
        references public.model_runs(id),
    provider text,
    bookmaker_key text,
    metadata jsonb not null default '{}'::jsonb,
    actual_value double precision,
    graded_at timestamptz,
    grading_metadata jsonb not null default '{}'::jsonb,

    unique (board_id, rank)
);

create table if not exists public.candidate_predictions (
    id bigint generated by default as identity primary key,
    model_run_id uuid not null
        references public.model_runs(id)
        on delete cascade,
    prop_snapshot_id bigint not null
        references public.prop_snapshots(id),
    predicted_probability double precision not null
        check (
            predicted_probability >= 0
            and predicted_probability <= 1
        ),
    rank integer,
    eligible boolean not null,
    exclusion_reason text,
    created_at timestamptz not null default now(),
    unique (model_run_id, prop_snapshot_id)
);

create table if not exists public.player_game_batting (
    id bigint generated by default as identity primary key,
    provider text not null default 'propline',
    provider_event_id text not null,
    sport_key text not null default 'baseball_mlb',
    game_date date not null,
    commence_time timestamptz,
    home_team text,
    away_team text,
    player_name text not null,
    normalized_player_name text not null,
    team text,
    opponent text,
    is_home boolean,
    hits integer,
    at_bats integer,
    plate_appearances integer,
    walks integer,
    strikeouts integer,
    total_bases integer,
    rbis integer,
    runs integer,
    home_runs integer,
    raw_payload jsonb not null default '{}'::jsonb,
    fetched_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint player_game_batting_provider_event_player_key
        unique (provider, provider_event_id, normalized_player_name)
);

create table if not exists public.batter_hits_training_examples (
    id bigint generated by default as identity primary key,
    prop_snapshot_id bigint not null
        references public.prop_snapshots(id),
    provider text not null,
    provider_event_id text not null,
    sport_key text not null,
    bookmaker_key text not null,
    market_key text not null,
    player_name text not null,
    normalized_player_name text not null,
    game_date date not null,
    commence_time timestamptz,
    home_team text,
    away_team text,
    line double precision not null,
    side text not null default 'over',
    actual_hits integer not null,
    target_over boolean not null,
    feature_version text not null,
    prior_games_3 integer,
    prior_games_5 integer,
    prior_games_10 integer,
    hits_last_3 integer,
    hits_last_5 integer,
    hits_last_10 integer,
    hit_rate_last_3 double precision,
    hit_rate_last_5 double precision,
    hit_rate_last_10 double precision,
    avg_hits_last_10 double precision,
    avg_at_bats_last_10 double precision,
    avg_plate_appearances_last_10 double precision,
    avg_total_bases_last_10 double precision,
    strikeout_rate_last_10 double precision,
    walk_rate_last_10 double precision,
    season_games_before integer,
    season_hits_before integer,
    season_hit_rate_before double precision,
    season_avg_hits_before double precision,
    has_prior_batting_history boolean not null default false,
    is_cold_start boolean not null default false,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists board_picks_board_id_idx
    on public.board_picks(board_id);

create unique index if not exists prop_snapshots_run_offer_uidx
    on public.prop_snapshots (
        ingestion_run_id,
        provider_event_id,
        bookmaker_key,
        market_key,
        outcome_name,
        player_name,
        line,
        coalesce(dfs_odds_type, '')
    );

create index if not exists prop_snapshots_ingestion_run_idx
    on public.prop_snapshots(ingestion_run_id);

create index if not exists prop_snapshots_provider_event_idx
    on public.prop_snapshots(provider, provider_event_id);

create index if not exists prop_snapshots_commence_time_idx
    on public.prop_snapshots(commence_time);

create index if not exists prop_snapshots_bookmaker_market_idx
    on public.prop_snapshots(bookmaker_key, market_key);

create index if not exists prop_snapshots_captured_at_idx
    on public.prop_snapshots(captured_at);

create index if not exists candidate_predictions_model_run_idx
    on public.candidate_predictions(model_run_id);

create index if not exists candidate_predictions_snapshot_idx
    on public.candidate_predictions(prop_snapshot_id);

create index if not exists player_game_batting_provider_event_idx
    on public.player_game_batting(provider_event_id);

create index if not exists player_game_batting_game_date_idx
    on public.player_game_batting(game_date);

create index if not exists player_game_batting_normalized_player_name_idx
    on public.player_game_batting(normalized_player_name);

create index if not exists player_game_batting_player_name_idx
    on public.player_game_batting(player_name);

create index if not exists player_game_batting_team_idx
    on public.player_game_batting(team);

create unique index if not exists batter_hits_training_examples_snapshot_uidx
    on public.batter_hits_training_examples(prop_snapshot_id);

create unique index if not exists batter_hits_training_examples_logical_uidx
    on public.batter_hits_training_examples (
        provider,
        provider_event_id,
        normalized_player_name,
        sport_key,
        market_key,
        bookmaker_key,
        line,
        side
    );

create index if not exists batter_hits_training_examples_game_date_idx
    on public.batter_hits_training_examples(game_date);

create index if not exists
    batter_hits_training_examples_normalized_player_name_idx
    on public.batter_hits_training_examples(normalized_player_name);

create index if not exists batter_hits_training_examples_provider_event_idx
    on public.batter_hits_training_examples(provider, provider_event_id);

create index if not exists batter_hits_training_examples_feature_version_idx
    on public.batter_hits_training_examples(feature_version);

create or replace function public.publish_daily_board(
    p_slate_date date,
    p_model_version text,
    p_status text,
    p_metadata jsonb,
    p_picks jsonb
)
returns void
language plpgsql
as $$
declare
    v_board_id bigint;
begin
    insert into public.daily_boards (
        slate_date,
        generated_at,
        model_version,
        status,
        metadata
    )
    values (
        p_slate_date,
        now(),
        p_model_version,
        p_status,
        coalesce(p_metadata, '{}'::jsonb)
    )
    on conflict (slate_date)
    do update set
        generated_at = excluded.generated_at,
        model_version = excluded.model_version,
        status = excluded.status,
        metadata = excluded.metadata
    returning id into v_board_id;

    delete from public.board_picks
    where board_id = v_board_id;

    insert into public.board_picks (
        board_id,
        rank,
        player_name,
        team,
        opponent,
        prop_type,
        line,
        side,
        model_probability,
        game_time,
        result_status,
        prop_snapshot_id,
        model_run_id,
        provider,
        bookmaker_key,
        metadata
    )
    select
        v_board_id,
        pick.rank,
        pick.player_name,
        pick.team,
        pick.opponent,
        pick.prop_type,
        pick.line,
        pick.side,
        pick.model_probability,
        pick.game_time,
        pick.result_status,
        pick.prop_snapshot_id,
        pick.model_run_id,
        pick.provider,
        pick.bookmaker_key,
        coalesce(pick.metadata, '{}'::jsonb)
    from jsonb_to_recordset(p_picks) as pick (
        rank integer,
        player_name text,
        team text,
        opponent text,
        prop_type text,
        line double precision,
        side text,
        model_probability double precision,
        game_time timestamptz,
        result_status text,
        prop_snapshot_id bigint,
        model_run_id uuid,
        provider text,
        bookmaker_key text,
        metadata jsonb
    );
end;
$$;

alter table public.daily_boards enable row level security;
alter table public.board_picks enable row level security;
alter table public.prop_ingestion_runs enable row level security;
alter table public.prop_snapshots enable row level security;
alter table public.model_runs enable row level security;
alter table public.candidate_predictions enable row level security;
alter table public.player_game_batting enable row level security;
alter table public.batter_hits_training_examples enable row level security;

grant all on table public.player_game_batting to service_role;
grant usage, select on sequence public.player_game_batting_id_seq
    to service_role;

grant all on table public.batter_hits_training_examples to service_role;
grant usage, select on sequence public.batter_hits_training_examples_id_seq
    to service_role;
