create table if not exists public.player_game_batting (
    id bigint generated by default as identity primary key,
    provider text not null default 'propline',
    provider_event_id text not null,
    sport_key text not null default 'baseball_mlb',
    game_date date not null,
    commence_time timestamptz,
    home_team text,
    away_team text,
    player_name text not null,
    normalized_player_name text not null,
    team text,
    opponent text,
    is_home boolean,
    hits integer,
    at_bats integer,
    plate_appearances integer,
    walks integer,
    strikeouts integer,
    total_bases integer,
    rbis integer,
    runs integer,
    home_runs integer,
    raw_payload jsonb not null default '{}'::jsonb,
    fetched_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint player_game_batting_provider_event_player_key
        unique (provider, provider_event_id, normalized_player_name)
);

create index if not exists player_game_batting_provider_event_idx
    on public.player_game_batting(provider_event_id);

create index if not exists player_game_batting_game_date_idx
    on public.player_game_batting(game_date);

create index if not exists player_game_batting_normalized_player_name_idx
    on public.player_game_batting(normalized_player_name);

create index if not exists player_game_batting_player_name_idx
    on public.player_game_batting(player_name);

create index if not exists player_game_batting_team_idx
    on public.player_game_batting(team);

alter table public.player_game_batting enable row level security;

grant all on table public.player_game_batting to service_role;
grant usage, select on sequence public.player_game_batting_id_seq
    to service_role;
