create table if not exists public.batter_hits_training_examples (
    id bigint generated by default as identity primary key,
    prop_snapshot_id bigint not null
        references public.prop_snapshots(id),
    provider text not null,
    provider_event_id text not null,
    sport_key text not null,
    bookmaker_key text not null,
    market_key text not null,
    player_name text not null,
    normalized_player_name text not null,
    game_date date not null,
    commence_time timestamptz,
    home_team text,
    away_team text,
    line double precision not null,
    side text not null default 'over',
    actual_hits integer not null,
    target_over boolean not null,
    feature_version text not null,
    prior_games_3 integer,
    prior_games_5 integer,
    prior_games_10 integer,
    hits_last_3 integer,
    hits_last_5 integer,
    hits_last_10 integer,
    hit_rate_last_3 double precision,
    hit_rate_last_5 double precision,
    hit_rate_last_10 double precision,
    avg_hits_last_10 double precision,
    avg_at_bats_last_10 double precision,
    avg_plate_appearances_last_10 double precision,
    avg_total_bases_last_10 double precision,
    strikeout_rate_last_10 double precision,
    walk_rate_last_10 double precision,
    season_games_before integer,
    season_hits_before integer,
    season_hit_rate_before double precision,
    season_avg_hits_before double precision,
    has_prior_batting_history boolean not null default false,
    is_cold_start boolean not null default false,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists batter_hits_training_examples_snapshot_uidx
    on public.batter_hits_training_examples(prop_snapshot_id);

create unique index if not exists batter_hits_training_examples_logical_uidx
    on public.batter_hits_training_examples (
        provider,
        provider_event_id,
        normalized_player_name,
        sport_key,
        market_key,
        bookmaker_key,
        line,
        side
    );

create index if not exists batter_hits_training_examples_game_date_idx
    on public.batter_hits_training_examples(game_date);

create index if not exists
    batter_hits_training_examples_normalized_player_name_idx
    on public.batter_hits_training_examples(normalized_player_name);

create index if not exists batter_hits_training_examples_provider_event_idx
    on public.batter_hits_training_examples(provider, provider_event_id);

create index if not exists batter_hits_training_examples_feature_version_idx
    on public.batter_hits_training_examples(feature_version);

alter table public.batter_hits_training_examples enable row level security;

grant all on table public.batter_hits_training_examples to service_role;
grant usage, select on sequence public.batter_hits_training_examples_id_seq
    to service_role;
